# Generated by Django 2.2.14 on 2020-07-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200709_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='lang',
            new_name='languange',
        ),
    ]
