# Generated by Django 2.2.14 on 2020-07-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200711_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all', 'View all borrowed books'),)},
        ),
    ]
