# Generated by Django 2.2.14 on 2020-07-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200711_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_do_stufs', 'Silebilir,Güncelleyebilir'),)},
        ),
    ]
